### ISSUE TITLE
OFFLINE: Audio stutters in standby if Waydroid is running in the background

### ISSUE THREAD

**Issue by PhilDevProg** [FakeShell/batman#4]
If Offline is enabled and Waydroid is running in the background, audio starts to stutter in standby mode. If Offline is turned off, audio works fine and doesn't stutter.

OS: Droidian trixie
Batman version: 16+git20231002005620 (up to date with branch 'all')
Device: Pixel 3a XL (bonito)
Tested apps: G4Music, Spot

**Comment by FakeShell** [comment]
the solution would be to check if any audio is being streamed through snd then cut the number of cores going offline in half making enough instructions go through at once to not make pulse stutter, i have some rough code but have not tested it yet, will take some time for it to land in production

**Comment by FakeShell** [comment]
please give the version from https://github.com/FakeShell/batman/commit/7d0dd33c333ea957e5c657f6df8600c5fc48bd35 (current latest) a try, i could not replicate the slowdowns even if waydroid was running in the background (telegram running in waydroid but nothing heavy)
