### ISSUE TITLE
POWERSAVE: Audio from Waydroid stutters in standby

### ISSUE THREAD

**Issue by PhilDevProg** [FakeShell/batman#5]
If Powersave is enabled, audio coming from Waydroid starts to stutter in standby mode. If Powersave is turned off, audio works fine and doesn't stutter in standby mode.

OS: Droidian trixie
Batman version: 16+git20231002005620 (up to date with branch 'all')
Device: Pixel 3a XL (bonito)
Tested apps: Spotify

**Comment by FakeShell** [comment]
This case will be rough, there is not much we can do to have both system power management AND a container running smoothly at the same time. it is more of a hardware limitation. I assume if waydroid is running and something is being streamed through snd only the first cluster can go down? needs more testing.

**Comment by FakeShell** [comment]
fixed with batman-nicerdicer, audio now plays smoothly when screen is off.
